project_id = "nivo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://nivo-lake.vercel.app"
additional_redirect_urls = [
  "http://localhost:5173/auth/callback",
  "http://localhost:5173/auth/reset-password",
  "https://nivo-lake.vercel.app/auth/callback",
  "https://nivo-lake.vercel.app/auth/reset-password"
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
